FROM golang:1.24.3-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o consumer ./cmd/consumer

# Final stage
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/consumer .

ENV REDPANDA_BROKER=redpanda:9092

CMD ["./consumer"]
