version: '3.8'

services:
  cassandra-db:
    image: cassandra:4.1
    container_name: cassandra-db
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'SELECT now() FROM system.local' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    environment:
      - CASSANDRA_CLUSTER_NAME=goanalytics-cluster
      - CASSANDRA_DC=dc1

  cassandra-init:
    image: cassandra:4.1
    depends_on:
      cassandra-db:
        condition: service_healthy
    volumes:
      - ./db/init.cql:/init.cql:ro
    entrypoint: [ "sh", "-c", "sleep 10 && cqlsh cassandra-db -f /init.cql" ]
    restart: "on-failure"

  app:
    build: .
    depends_on:
      cassandra-init:
        condition: service_completed_successfully
    ports:
      - "7000:7000"
    volumes:
      - ./config.json:/config.json
    environment:
      - CASSANDRA_HOST=cassandra-db
