apiVersion: batch/v1
kind: Job
metadata:
  name: cassandra-init
spec:
  template:
    spec:
      containers:
        - name: cassandra-init
          image: cassandra:4.1
          command:
            - "sh"
            - "-c"
            - |
              echo "[INIT] Waiting for Cassandra to be available..."
              until cqlsh cassandra -e "DESCRIBE KEYSPACES" > /dev/null 2>&1; do
                echo "[WAIT] Cassandra not ready yet..."; sleep 2;
              done

              echo "[INIT] Cassandra is ready! Applying schema..."
              cqlsh cassandra -f /init.cql
              echo "[INIT] ✅ Schema applied"
          volumeMounts:
            - name: init-cql
              mountPath: /init.cql
              subPath: init.cql
      restartPolicy: OnFailure
      volumes:
        - name: init-cql
          configMap:
            name: cassandra-schema
