apiVersion: batch/v1
kind: Job
metadata:
  name: redpanda-topic-init
spec:
  template:
    spec:
      containers:
        - name: rpk
          image: docker.redpanda.com/redpandadata/redpanda:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo '[INIT] Waiting for Redpanda...';
              until rpk cluster info --brokers=redpanda:9092 > /dev/null 2>&1; do
                echo '[INIT] Redpanda not ready yet...'; sleep 2;
              done;

              echo '[INIT] Creating topic wikipedia.protobuf...';
              until rpk topic create wikipedia.protobuf --brokers=redpanda:9092 > /dev/null 2>&1; do
                echo '[INIT] Retrying topic creation...'; sleep 2;
              done;

              echo '[INIT] ✅ Topic created!';
      restartPolicy: OnFailure
