name: CI/CD - ch-6

on:
  push:
    paths:
      - 'ch-6/**'
      - '.github/workflows/ci-ch6.yml'
  pull_request:
    paths:
      - 'ch-6/**'
      - '.github/workflows/ci-ch6.yml'

jobs:
  test-build-push:
    name: Test, Build, Push, Verify Observability
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.5
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Run Go tests
      run: go test ./ch-6/... -v -cover

    - name: Build Docker images
      run: docker-compose -f ch-6/docker-compose.yml build

    - name: Start services
      run: docker-compose -f ch-6/docker-compose.yml up -d

    - name: Wait for /metrics endpoint
      run: |
        echo "Waiting for /metrics endpoint to be ready..."
        for i in {1..30}; do
          if curl -sSf http://localhost:8080/metrics > /dev/null; then
            echo "✅ /metrics is up"
            break
          fi
          echo "⏳ Waiting ($i/30)..."
          sleep 2
        done

    - name: Display /metrics sample
      run: curl -s http://localhost:8080/metrics | head -n 20

    - name: Wait for Prometheus and Grafana
      run: |
        echo "Waiting for Prometheus..."
        for i in {1..30}; do
          if curl -sSf http://localhost:9090/-/healthy > /dev/null; then
            echo "✅ Prometheus is healthy"
            break
          fi
          echo "⏳ Waiting for Prometheus ($i/30)..."
          sleep 2
        done

        echo "Waiting for Grafana..."
        for i in {1..30}; do
          if curl -sSf http://localhost:3000/login > /dev/null; then
            echo "✅ Grafana is responding"
            break
          fi
          echo "⏳ Waiting for Grafana ($i/30)..."
          sleep 2
        done

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push producer image to GHCR
      run: |
        docker tag ch-6_producer ghcr.io/${{ github.repository }}/ch-6-producer:latest
        docker push ghcr.io/${{ github.repository }}/ch-6-producer:latest

    - name: Push consumer image to GHCR
      run: |
        docker tag ch-6_consumer ghcr.io/${{ github.repository }}/ch-6-consumer:latest
        docker push ghcr.io/${{ github.repository }}/ch-6-consumer:latest

    - name: Tear down services
      run: docker-compose -f ch-6/docker-compose.yml down -v
